### ISSUE TITLE
bug(reload): reload gif

### ISSUE THREAD

**Issue by IllanoAyala** [IllanoAyala/Music#3]

**Comment by LyubomirT** [comment]
Could you please elaborate on the issue? I don't really understand what you mean by "reload gif bug".

**Comment by IllanoAyala** [comment]
It was just a note for me to remember to correct later. Basically, if you press the reload button several times, many reload gifs will be added.

**Comment by LyubomirT** [comment]
> It was just a note for me to remember to correct later. Basically, if you press the reload button several times, many reload gifs will be added.

Oh, okay. Sorry for bothering you then.

**Comment by IllanoAyala** [comment]
It's okay, no problem. (If you have time, test the project and let me know what you think.)
